apiVersion: v1
kind: ConfigMap
metadata:
  name: driver-config
data:
  SPRING_PROFILES_ACTIVE: docker
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/driver_db
  SPRING_DATASOURCE_USERNAME: postgres
  SERVER_PORT: "8082"
